### ISSUE TITLE
Errors with the editor Physicanim ragdoll builder aswell and issues with the Runtime physicanimator component

### ISSUE THREAD

**Issue by SwixDevs** [TildeAsterisk/Physicanim-FREE#3]
Hello,
First of all, let me just say that I think this package has a lot of potential! I tried the active ragdoll generator using the provided demo model and it looks promising.
That said, when I try to use the active ragdoll generator, it just doesn't work properly for anything that isn't your demo model. It gave me an error and stopped generating the ragdoll when I tried it on my own humanoid model.

`NullReferenceException: Object reference not set to an instance of an object
ActiveRagdollBuilder.SetupJointMatch (UnityEngine.GameObject sAnimObj) (at Assets/Plugins/Physicanim/Scripts/Editor/ActiveRagdollBuilder.cs:547)
ActiveRagdollBuilder.OnWizardCreate () (at Assets/Plugins/Physicanim/Scripts/Editor/ActiveRagdollBuilder.cs:191)
PhysicanimGUI.OnGUI () (at Assets/Plugins/Physicanim/Scripts/Editor/PhysicanimGUI.cs:65)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <68089899e4c84456bfc1de3436accf4a>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <68089899e4c84456bfc1de3436accf4a>:0)
UnityEditor.DockArea.OldOnGUI () (at <68089899e4c84456bfc1de3436accf4a>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <9c79dfaa81ca4dafa70d4219450af5e1>:0)`

After this, when I generate an active ragdoll using the demo model, it successfully generates, but then none of the settings seem to work on the Physicanimator component.

I moved the ragdoll around in its T-Pose and I can see how it reacts to collisions, but there's also no actual physics, what I mean by that is that the ragdoll doesn't fall down on the ground and try to balance, it stays in the air and only reacts to collisions (which is perfect, I just thought it would fall down on the ground and balance itself.)

I hope you continue development on this package, it's quite intriguing where it can lead to!

**Comment by TildeAsterisk** [comment]
Hi Swix,
Thank you for using Physicanim, I'm sorry that you encountered this issue when using my Active Ragdoll System Asset Package. This error usually occurs when the wrong object is selected in the hierarchy while trying to create the active ragdoll.
Thank you for reaching out to me and taking time to give me feedback , it is much appreciated. I have fixed this issue and would be happy to offer you further support with your development. I wish you all the best with your next game soon to be released on Steam. I will be keeping an eye out for your projects.
Kind regards,
-Tilde Asterisk
